simulated_robot:
  ros__parameters:
    blocked: true
robot_tree:
  ros__parameters:
    tick_period: 0.05
minimal_tree:
  ros__parameters:
    tick_period: 0.05
simulated_action_server:
  ros__parameters:
    step_seconds: 0.04
